# --- General Settings ---
excel_file: './data/master_data.xlsx'   # Default file if detail file_path isn't specified
output_target: excel                  # 'json' or 'excel'
output_json_file: './output/aggregated_data.json' # Used if output_target is json
output_excel_file: './output/aggregated_flat_data.xlsx' # Used if output_target is excel
# output_format: dict                 # This applies only to JSON output ('dict' or 'list')

# --- Master Sheet ---
master_sheet:
  name: Customers
  primary_key_column: CustomerID
  include_columns:
    CustomerID: MasterCustomerID  # Renaming PK for clarity in output
    CompanyName: CompanyName
    ContactName: ContactName
    City: City

# --- Detail Sheets ---
detail_sheets:
  - json_key: orders            # Still useful for internal logic/potential JSON use
    sheet_name: OrderData       # Sheet name within its file
    file_path: './data/orders_details.xlsx' # Specific file for orders
    foreign_key_column: CustID  # Column in OrderData linking to CustomerID
    include_columns:
      OrderID: OrderID
      OrderDate: OrderDate
      Freight: FreightCost     # Rename Freight -> FreightCost

  - json_key: support_tickets
    sheet_name: Tickets         # Sheet name within its file
    # file_path: not specified, so defaults to './data/master_data.xlsx'
    foreign_key_column: ClientRef # Column in Tickets linking to CustomerID
    include_columns:
      TicketID: SupportTicketID # Rename TicketID
      OpenedDate: TicketOpenedDate
      Status: TicketStatus
      # Note: We are NOT including 'ClientRef' here, so it won't be in the final output

# --- Optional: Define final Excel column order ---
# excel_column_order:
#  - MasterCustomerID
#  - CompanyName
#  - ContactName
#  - City
#  - OrderID
#  - OrderDate
#  - FreightCost
#  - SupportTicketID
#  - TicketOpenedDate
#  - TicketStatus