# config.yaml

# --- General Settings ---
# Specify the 'master' file here. Detail files can override this.
excel_file: './master_app_list_q4.xlsx'
output_target: excel                # Target 'excel' for the flat file output
# output_json_file: './output/aggregated_data.json' # Define even if not used now
output_excel_file: './output/aggregated_security_posture.xlsx' # Desired output Excel path

# --- Master Sheet ---
master_sheet:
  name: Sheet1                     # Default sheet name for CSV/Excel
  primary_key_column: Application ID # The unique ID in the master list
  include_columns:
    # Mapping: { "Original Column Name": "Desired Output Column Name" }
    Application ID: MasterAppID    # Rename PK for clarity in output
    Grade: AppGrade
    Application Name: ApplicationName
    Business Owner: BusinessOwner
    Status: AppStatus              # Status from the master list

# --- Detail Sheets ---
detail_sheets:
  # 1. Exceptions Log
  - json_key: exceptions           # Identifier, less critical for Excel output but still needed
    sheet_name: Sheet1             # Default sheet name
    file_path: './exceptions_log_current.xlsx' # Path to the exceptions data
    foreign_key_column: App ID     # Column in exceptions linking to master 'Application ID'
    include_columns:
      # Mapping for exceptions columns. DO NOT include 'App ID' here.
      Exception ID: ExceptionID
      Summary: ExceptionSummary
      Risk: ExceptionRisk
      Approval Status: ExceptionApprovalStatus
      Expiry Date: ExceptionExpiryDate

  # 2. Infrastructure Scan Results
  - json_key: infra_scans
    sheet_name: Sheet1
    file_path: './infra_scan_results_oct.xlsx' # Path to infra scan data
    foreign_key_column: Target App ID # Column in infra scans linking to master 'Application ID'
    include_columns:
      # Mapping for infra scan columns. DO NOT include 'Target App ID' here.
      FindingID: InfraFindingID
      Finding Summary: InfraFindingSummary
      Rating: InfraRating
      Description: InfraDescription
      Status: InfraStatus          # Status from the infra scan findings
      Hostname: InfraHostname

  # 3. Web Vulnerability Scan Results
  - json_key: web_vulns
    sheet_name: Sheet1
    file_path: './web_vuln_scan_nov.xlsx' # Path to web vuln data
    foreign_key_column: CARID      # Column in web vulns linking to master 'Application ID'
    include_columns:
      # Mapping for web vuln columns. DO NOT include 'CARID' here.
      Vulnerability ID: WebVulnID
      Vulnerability Name: WebVulnName
      Severity: WebVulnSeverity
      Details: WebVulnDetails
      Finding Status: WebVulnFindingStatus # Status from the web vuln scan
      Opinion: WebVulnOpinion

# --- Optional: Define final Excel column order ---
# This controls the column sequence in the output .xlsx file
excel_column_order:
  # Master Application Info
  - MasterAppID
  - ApplicationName
  - AppGrade
  - BusinessOwner
  - AppStatus
  # Exception Details
  - ExceptionID
  - ExceptionSummary
  - ExceptionRisk
  - ExceptionApprovalStatus
  - ExceptionExpiryDate
  # Infrastructure Finding Details
  - InfraFindingID
  - InfraFindingSummary
  - InfraRating
  - InfraDescription
  - InfraStatus
  - InfraHostname
  # Web Vulnerability Details
  - WebVulnID
  - WebVulnName
  - WebVulnSeverity
  - WebVulnDetails
  - WebVulnFindingStatus
  - WebVulnOpinion