# config_summary_grouped.yaml

# --- Output Settings ---
output_file: './output/application_summary_report_grouped.xlsx'

# --- Master Source ---
master_source:
  file_path: './master_app_list_q4.xlsx'
  sheet_name: Sheet1
  primary_key_column: Application ID
  include_master_columns:
    Application ID: AppID
    Application Name: ApplicationName
    Business Owner: BusinessOwner
    Grade: AppGrade
    Status: MasterAppStatus

# --- Detail Sources and their Summaries ---
detail_sources: # List of source files/sheets

  # Group 1: Summaries from the Exceptions Log
  - file_path: './exceptions_log_current.xlsx' # Define source once
    sheet_name: Sheet1
    foreign_key_column: App ID
    summaries: # List of summaries derived from this source
      - output_column_name: HasPendingException
        aggregation: exists
        filters:
          - column: Approval Status
            operator: ==
            value: Pending
      - output_column_name: ActiveApprovedExceptionCount
        aggregation: count
        filters:
          - column: Approval Status
            operator: ==
            value: Approved
          - column: Expiry Date
            operator: '>='
            value: 'TODAY'
      - output_column_name: ExpiredExceptionCount
        aggregation: count
        filters:
          - column: Expiry Date
            operator: '<'
            value: 'TODAY'
      - output_column_name: HighOrMediumRiskExceptionCount
        aggregation: count
        filters:
          - column: Risk
            operator: in
            value: ['High', 'Medium']
          - column: Approval Status
            operator: in
            value: ['Approved', 'Pending']
      - output_column_name: ExceptionMissingRisk
        aggregation: exists
        filters:
          - column: Risk
            operator: isnull
      - output_column_name: LowRiskApprovedExceptionCount
        aggregation: count
        filters:
          - column: Risk
            operator: in
            value: ['Low', 'Acceptable']
          - column: Approval Status
            operator: ==
            value: Approved
          - column: Summary
            operator: not in
            value: ['Standard Renewal', 'Temporary Access Granted']

  # Group 2: Summaries from Infrastructure Scans
  - file_path: './infra_scan_results_oct.xlsx'
    sheet_name: Sheet1
    foreign_key_column: Target App ID
    summaries:
      - output_column_name: UrgentInfraFindingCount
        aggregation: count
        filters:
          - column: Rating
            operator: ==
            value: Urgent
          - column: Status
            operator: in
            value: ['Action Needed', 'Needs Review']
      - output_column_name: HasLog4jFinding
        aggregation: exists
        filters:
          - column: Finding Summary
            operator: contains
            value: 'log4j'
      - output_column_name: CRMWebFindingCount
        aggregation: count
        filters:
          - column: Hostname
            operator: startswith
            value: 'vm-crm-web-'
      - output_column_name: UrgentFindingWithDesc
        aggregation: count
        filters:
          - column: Description
            operator: notnull
          - column: Rating
            operator: ==
            value: Urgent

  # Group 3: Summaries from Web Vuln Scans
  - file_path: './web_vuln_scan_nov.xlsx'
    sheet_name: Sheet1
    foreign_key_column: CARID
    summaries:
      - output_column_name: CriticalOpenWebVulnCount
        aggregation: count
        filters:
          - column: Severity
            operator: ==
            value: Critical
          - column: Finding Status
            operator: ==
            value: Open
      - output_column_name: HasSQLiOrXSS
        aggregation: exists
        filters:
          - column: Vulnerability Name
            operator: regex
            value: '(?i)(SQL Injection|Cross-Site Scripting)'
          - column: Finding Status
            operator: in
            value: ['Open', 'Patched']

  # Group 4: Summaries from Code Scans
  - file_path: './code_scan_results.xlsx'
    sheet_name: Sheet1
    foreign_key_column: AppRefID
    summaries:
      - output_column_name: TotalSecretsFoundHighSev
        aggregation: sum
        aggregation_column: SecretCount
        filters:
          - column: SeverityRating
            operator: '>='
            value: 4
          - column: Status
            operator: '!='
            value: 'False Positive'
      - output_column_name: PHPScriptSecretCount
        aggregation: sum
        aggregation_column: SecretCount
        filters:
          - column: FilePath
            operator: endswith
            value: '.php'
      - output_column_name: HasSensitiveFileFinding
        aggregation: exists
        filters:
          - column: FilePath
            operator: regex
            value: '(?i)(\.pem$|\.key$|\.p12$|/id_rsa)'
          - column: Status
            operator: '!='
            value: 'False Positive'


# --- Optional: Define final Excel column order ---
excel_column_order:
  # Master Info
  - AppID
  - ApplicationName
  - BusinessOwner
  - AppGrade
  - MasterAppStatus
  # Exception Summaries
  - HasPendingException
  - ActiveApprovedExceptionCount
  - ExpiredExceptionCount
  - HighOrMediumRiskExceptionCount
  - ExceptionMissingRisk
  - LowRiskApprovedExceptionCount
  # Infra Scan Summaries
  - UrgentInfraFindingCount
  - HasLog4jFinding
  - CRMWebFindingCount
  - UrgentFindingWithDesc
  # Web Vuln Summaries
  - CriticalOpenWebVulnCount
  - HasSQLiOrXSS
  # Code Scan Summaries
  - TotalSecretsFoundHighSev
  - PHPScriptSecretCount
  - HasSensitiveFileFinding